In [1]:
import numpy as np
import sys
import time

In [9]:
arr1=np.array([1,2,3,4,5,6,6,6])
arr2=np.array((1,2,3,4,5,6,))
print(arr1)

print("type :" ,type(arr1))
print("type :" ,type(arr2))
print("shape :" ,type(arr1.shape))
print("shape :" ,type(arr2.shape))
print("shape :" ,arr1.shape) # print the actual shape of the array (rows, columns)
print("shape :" ,arr2.shape) # print the actual shape of the array (rows, columns)


[1 2 3 4 5 6 6 6]
type : <class 'numpy.ndarray'>
type : <class 'numpy.ndarray'>
shape : <class 'tuple'>
shape : <class 'tuple'>
shape : (8,)
shape : (6,)


In [12]:
twodnumpy = np.array([[1,2,3],[4,5,6]])
print(twodnumpy)

print("shape :" ,type(twodnumpy.shape))
print("shape :" ,twodnumpy.shape)

[[1 2 3]
 [4 5 6]]
shape : <class 'tuple'>
shape : (2, 3)


In [19]:
list_data=list(range(1000))
numpy_data=np.array(list_data)
# print(list_data)
# print(numpy_data)
print("python list size: " ,sys.getsizeof(list_data)*len(list_data) , "Bytes")
print("numpy array list : ", numpy_data.nbytes , "bytes")

python list size:  8056000 Bytes
numpy array list :  8000 bytes


In [2]:
import numpy as np
import time

size=10000
list1=list(range(size))
list2=list(range(size))

# python list 
start = time.time()
result=[x+y for x,y in zip(list1,list2)]
end=time.time()
print("Python time: ", end-start)


# numpy aray

arr1=np.array(list1)
arr2=np.array(list2)

start = time.time()
result=arr1+arr2
end=time.time()
print("numpy time : ",end-start)

Python time:  0.0007145404815673828
numpy time :  0.0003330707550048828


In [9]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
list_square = [n**2 for n in nums]
print(list_square)

arr3=np.array((1,2,3,4,5,6,))
numpy_sq=arr3*2
print(numpy_sq)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[ 2  4  6  8 10 12]
