In [1]:
import numpy as np

In [5]:
# from python lists

# 1D array
arr1=np.array([1,2,3,4,5,6])
print(arr1)

# 2D arrays
arr2=np.array([[1,2,3],[1,2,3]])
print(arr2)

[1 2 3 4 5 6]
[[1 2 3]
 [1 2 3]]


In [20]:
# creating array from scatch

print(np.zeros((3,3)))
print(np.ones((3,3)))
print(np.full((3,30),6))
print(np.eye(3))
print(np.arange(2,10,2))
print(np.linspace(2,10,7))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[2 4 6 8]
[ 2.          3.33333333  4.66666667  6.          7.33333333  8.66666667
 10.        ]


In [24]:
# checking array properties
import numpy as np

arr=np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(" shape : ",arr.shape)
print(" size : ",arr.size)
print(" dimension : ",arr.ndim)
print(" Data Type : ", arr.dtype)

 shape :  (4, 6)
 size :  24
 dimension :  2
 Data Type :  int64


In [27]:
# changing data type

# explicit data type
arr=np.array([1,2,3,4],dtype=np.float32)
print(arr)
print(arr.dtype)

# convert to another type
arr_int=arr.astype(np.int32)
print(arr_int)
print(arr_int.dtype)


[1. 2. 3. 4.]
float32
[1 2 3 4]
int32


In [30]:
# reShaping and flattering arrays

arr=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

# reshape to 2x3 -> 3X2:
reshape=arr.reshape((3,2))
print(reshape)

# flatten : 2D -> 1D :
flattend=arr2.flatten()
print(flattend)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
