In [2]:
import numpy as np

In [6]:
arr= np.array([10,20 , 30 ,40 , 50])
print(arr[0])
# print(arr[10])
print(arr[0:9])
print(arr[9:11])
print(arr[3:5:7])
print(arr[::-1])


10
[10 20 30 40 50]
[]
[40]
[50 40 30 20 10]


In [20]:
arr=np.array([[2,3,4,5],[3,4,5,6]])
print(arr)

print(arr[0,2])
print(arr[0:2,1:3]) # rows:coluns

[[2 3 4 5]
 [3 4 5 6]]
4
[[3 4]
 [4 5]]


In [31]:
# not same as python list and copy

arr=np.array([2,3,4,5])
sliced=arr[1:5]
print(arr.shape)
print(arr)
print(sliced)

sliced[0]=9999999
print("arr:",arr)
print("sli:",sliced)


(4,)
[2 3 4 5]
[3 4 5]
arr: [      2 9999999       4       5]
sli: [9999999       4       5]


In [35]:
# we have to use , copy()

arr=np.array([2,3,4,5])
sliced=arr[1:5].copy()
print(arr)
print(sliced)

sliced[0]=9999999
print("arr:",arr)
print("sli:",sliced)

[2 3 4 5]
[3 4 5]
arr: [2 3 4 5]
sli: [9999999       4       5]


In [45]:
# fancy indexing

arr=np.array([2,3,4,5])
index=[1,3]
print(arr[index])

arr2=np.array([[2,3,4,5],[3,4,5,6]])
print(arr2[[0,1],[1,2]])

[3 5]
[3 5]


In [48]:
# boolean masking (filtering arrays)

arr=np.array([25,36,40,59])
arr2=arr>1
arr3=arr%2==0
print(arr)
print(arr3)

[25 36 40 59]
[False  True  True False]
